services:
  db:
    image: postgres:15-alpine
    container_name: webtechview_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secure_pass_123
      POSTGRES_DB: webtechview
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
